apiVersion: v2
name: ejabberd
description: ejabberd XMPP server helm chart
type: application
version: 0.1.0
appVersion: "23.04-k8s"
keywords:
  - xmpp
  - mqtt
  - sip
  - stun
  - turn
dependencies:
  - name: reloader
    repository: https://stakater.github.io/stakater-charts
    version: 1.0.29
    condition: reloader.install

maintainers:
  - name: saarko
    email: saarko@tutanota.com
