global:
  postgresql:
    auth:
      postgresPassword: "postgres"
      username: "ejabberd"
      password: "ejabberd"
      database: "ejabberd"

architecture: standalone
primary:
  name: primary
  nodeSelector:
    backend: sql
  persistence:
    enabled: true
    #existingClaim: "pvc-sql"
    storageClass: "standard"
