statefulSet:
  replicas: 3

healthCheck:
  tcpPort: 5210

service:
  type: NodePort

hosts:
  - example.com

certFiles:
  secretName:
    - custom-cert
  sideCar:
    enabled: true
    createRbac: true

logging:
  loglevel: debug

listen:
  http:
    expose: true
    nodePort: 30280
    options:
      request_handlers:
        /api: mod_http_api
  https:
    nodePort: 30443
    options:
      request_handlers:
        /api: mod_http_api

sqlDatabase:
  enabled: true
  defaultDb: sql
  newSqlSchema: true
  config:
    sql_type: mysql
    sql_server: mariadb.default.svc.cluster.local
    sql_port: 3306
    sql_database: ejabberd
    sql_username: ejabberd
    sql_password: ejabberd
  flyway:
    enabled: true
    keyValue: "?useSSL=false"
    mysqlFlavor: "mariadb"

authentification:
  auth_method:
   - sql
