#
# https://github.com/jp-gouin/helm-openldap/tree/master/.bin
#
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraMounts:
    - hostPath: /tmp/kind-worker
      containerPath: /tmp/kind-worker
  extraPortMappings:
  - containerPort: 5222
    hostPort: 30222
    protocol: TCP
  - containerPort: 5280
    hostPort: 30280
    protocol: TCP
  - containerPort: 30443
    hostPort: 30443
    protocol: TCP
  labels:
    backend: sql
- role: worker
- role: worker
