statefulSet:
  replicas: 3

healthCheck:
  tcpPort: 5210

service:
  type: NodePort

hosts:
  - example.com

certFiles:
  secretName:
    - custom-cert
  sideCar:
    enabled: true
    createRbac: true

logging:
  loglevel: debug

listen:
  http:
    expose: true
    nodePort: 30280
    options:
      request_handlers:
        /api: mod_http_api
  https:
    nodePort: 30443
    options:
      request_handlers:
        /api: mod_http_api

sqlDatabase:
  enabled: true
  defaultDb: sql
  config:
    sql_database: ejabberdTest1234
    sql_username: ejabberdTest1234
    sql_password: ejabberdTest1234_
  flyway:
    enabled: true

authentification:
  auth_method:
   - sql
