fullnameOverride: "mariadb"
architecture: standalone
auth:
  rootPassword: "ejabberdTest1234"
  database: ejabberdTest1234
  username: "ejabberdTest1234"
  password: "ejabberdTest1234_"
  primary:
    nodeSelector:
      backend: sql
    persistence:
      enabled: false
