apiVersion: v2
name: ejabberd
description: ejabberd XMPP server helm chart
type: application
version: 0.7.1
appVersion: "24.02-k8s1"
keywords:
  - xmpp
  - mqtt
  - sip
  - stun
  - turn

maintainers:
  - name: saarko
    email: saarko@tutanota.com
