{{- if .Values.sqlDatabase.enabled }}
{{- if .Values.sqlDatabase.flyway.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ejabberd.fullname" . }}-flyway-config
  namespace: {{ template "ejabberd.namespace" . }}
  labels:
    {{- include "ejabberd.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded
stringData:
  flyway.conf: |-
    {{- if (eq (toString .Values.sqlDatabase.config.sql_type) "pgsql") }}
    flyway.url=jdbc:postgresql://{{ default "ejabberd" .Values.sqlDatabase.config.sql_server }}:{{ default 5432 .Values.sqlDatabase.config.sql_port }}/{{ default "ejabberd" .Values.sqlDatabase.config.sql_database }}{{ .Values.sqlDatabase.flyway.keyValue }}
    {{- end }}
    {{- if (eq (toString .Values.sqlDatabase.config.sql_type) "mysql") }}
    flyway.url=jdbc:{{ default "mysql" .Values.sqlDatabase.flyway.mysqlFlavor }}://{{ default "ejabberd" .Values.sqlDatabase.config.sql_server }}:{{ default 3306 .Values.sqlDatabase.config.sql_port }}/{{ default "ejabberd" .Values.sqlDatabase.config.sql_database }}{{ .Values.sqlDatabase.flyway.keyValue }}
    {{- end }}
    flyway.user={{ default "ejabberd" .Values.sqlDatabase.config.sql_user }}
    flyway.password={{ default "ejabberd" .Values.sqlDatabase.config.sql_password }}
    {{- if .Values.sqlDatabase.flyway.options }}
    flyway.baselineVersion={{ default 23.04 .Values.sqlDatabase.flyway.baselineVersion }}
    flyway.baselineDescription=ejabberd
    {{- end }}
{{- end }}
{{- end }}
